[versions]
androidGradlePlugin = "8.4.1"
androidxActivityKotlin = "1.8.2"
androidxAnnotation = "1.7.1"
androidxAppCompat = "1.6.1"
androidxConcurrent = "1.1.0"
androidxCoreKotlin = "1.12.0"
androidxHiltNavigationCompose = "1.2.0"
androidxLifecycle = "2.7.0"
androidxNavigationComposeVersion = "2.7.7"
androidxTestCoreKotlin = "1.5.0"
androidxTest = "1.5.0"
androidxTestEspresso = "3.5.1"
androidxTestExtJunit = "1.1.5"
androidxTestExtTruth = "1.5.0"
androidxTestRunner = "1.5.2"
apacheCommonsCollections4 = "4.4"
apacheCommonsIo = "1.3.2"
apacheCommonsLang3 = "3.9"
apacheCommonsMath3 = "3.6.1"
coil = "2.4.0"
compileSdk = "34"
composeAminationBeta = "1.7.0-beta02"
composeBom = "2024.05.00"
datastorePreferences = "1.0.0"
googlePlayReview = "2.0.1"
hilt = "2.51"
jacoco = "0.8.10"
junit4 = "4.13.2"
kotlin = "2.0.0"
kotlinCoroutines = "1.7.1"
media3 = "1.3.0"
ksp = "2.0.0-1.0.21"
minSdk = "23"
mockitoInline = "3.7.7"
mockitoKotlin = "4.1.0"
room = "2.6.1"
robolectric = "4.10"
sonarqube = "4.2.1.3168"
targetSdk= "34"
uiAutomator = "2.3.0-beta01"
coreKtx = "1.13.1"

[libraries]
androidx-activity-kotlin = { group =  "androidx.activity", name =  "activity-ktx", version.ref = "androidxActivityKotlin" }
androidx-annotation = { group = "androidx.annotation", name = "annotation", version.ref = "androidxAnnotation" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "androidxAppCompat" }
androidx-compose-activity = { group = "androidx.activity", name = "activity-compose", version.ref = "androidxActivityKotlin" }
androidx-compose-animation-beta = { group = "androidx.compose.animation", name = "animation", version.ref = "composeAminationBeta" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-concurrent-futures-kotlin = { group =  "androidx.concurrent", name = "concurrent-futures-ktx", version.ref = "androidxConcurrent" }
androidx-compose-foundation = { group = "androidx.compose.foundation", name = "foundation" }
androidx-compose-foundation-layout = { group = "androidx.compose.foundation", name = "foundation-layout" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-compose-material3-windowsizes = { group = "androidx.compose.material3", name = "material3-window-size-class" }
androidx-compose-material-icons-core = { group = "androidx.compose.material", name = "material-icons-core" }
androidx-compose-material-icons-extended = { group = "androidx.compose.material", name = "material-icons-extended" }
androidx-compose-navigation = { group = "androidx.navigation", name = "navigation-compose", version = "2.7.7" }
androidx-compose-runtime = { group = "androidx.compose.runtime", name = "runtime" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-compose-ui-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-compose-ui-test = { group = "androidx.compose.ui", name = "ui-test" }
androidx-compose-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-core-kotlin = { group = "androidx.core", name = "core-ktx", version.ref = "androidxCoreKotlin" }
androidx-datastore-preferences = { group = "androidx.datastore", name = "datastore-preferences", version.ref =  "datastorePreferences" }
androidx-hilt-navigation-compose = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "androidxHiltNavigationCompose" }
androidx-lifecycle-viewmodel-savedstate = { group =  "androidx.lifecycle", name = "lifecycle-viewmodel-savedstate", version.ref = "androidxLifecycle" }
androidx-lifecycle-viewmodel-kotlin = { group =  "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "androidxLifecycle" }
androidx-lifecycle-viewmodel-compose = { group =  "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "androidxLifecycle" }
androidx-media3-common = { group = "androidx.media3", name = "media3-common", version.ref= "media3"}
androidx-media3-testutils = { group = "androidx.media3", name = "media3-test-utils", version.ref= "media3"}
androidx-media3-testutils-robolectric = { group = "androidx.media3", name = "media3-test-utils-robolectric", version.ref= "media3"}
androidx-media3-exoplayer = { group = "androidx.media3", name = "media3-exoplayer", version.ref= "media3"}
androidx-media3-exoplayer-dash = { group = "androidx.media3", name = "media3-exoplayer-dash", version.ref= "media3"}
androidx-media3-session = { group = "androidx.media3", name = "media3-session", version.ref= "media3"}
androidx-media3-ui = { group = "androidx.media3", name = "media3-ui", version.ref= "media3"}
androidx-room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }
androidx-room-kotlin = { group = "androidx.room", name = "room-ktx", version.ref = "room" }
androidx-room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
androidx-test-core = { module = "androidx.test:core", version.ref = "androidxTest" }
androidx-test-core-kotlin = { group = "androidx.test", name = "core-ktx", version.ref =  "androidxTestCoreKotlin" }
androidx-test-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "androidxTestEspresso" }
androidx-test-ext-junit = { module = "androidx.test.ext:junit", version.ref = "androidxTestExtJunit" }
androidx-test-ext-truth = { module = "androidx.test.ext:truth", version.ref = "androidxTestExtTruth" }
androidx-test-rules = { module = "androidx.test:rules", version.ref = "androidxTest" }
androidx-test-runner = { group = "androidx.test", name = "runner", version.ref = "androidxTestRunner" }
androidx-uiautomator = { group = "androidx.test.uiautomator", name = "uiautomator", version.ref="uiAutomator" }
android-gradlePlugin = { group = "com.android.tools.build", name = "gradle", version.ref = "androidGradlePlugin" }
apache-commons-io = { group = "org.apache.commons", name = "commons-io", version.ref = "apacheCommonsIo" }
apache-commons-collections4 = { group = "org.apache.commons", name= "commons-collections4", version.ref = "apacheCommonsCollections4" }
apache-commons-lang3 = { group = "org.apache.commons", name = "commons-lang3", version.ref = "apacheCommonsLang3"}
apache-commons-math3 = { group= "org.apache.commons", name = "commons-math3", version.ref = "apacheCommonsMath3" }
coil-compose = { group = "io.coil-kt", name = "coil-compose", version.ref = "coil" }
coil-test = { group = "io.coil-kt", name = "coil-test", version.ref = "coil" }
google-play-review = { group = "com.google.android.play", name = "review", version.ref = "googlePlayReview" }
google-play-review-ktx = { group = "com.google.android.play", name = "review-ktx", version.ref = "googlePlayReview" }
junit4 = { group = "junit", name = "junit", version.ref = "junit4"}
hilt-android-core = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-android-testing = { group = "com.google.dagger", name = "hilt-android-testing", version.ref = "hilt" }
hilt-compiler = { group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "hilt" }
kotlin-gradlePlugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
kotlin-stdlib = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib", version.ref = "kotlin" }
kotlin-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "kotlinCoroutines" }
kotlin-coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "kotlinCoroutines" }
kotlin-coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "kotlinCoroutines" }
ksp-gradlePlugin = { group = "com.google.devtools.ksp", name = "com.google.devtools.ksp.gradle.plugin", version.ref = "ksp" }
mockito-inline = { group = "org.mockito", name = "mockito-inline", version.ref = "mockitoInline" }
mockito-kotlin = { group = "org.mockito.kotlin", name = "mockito-kotlin", version.ref = "mockitoKotlin" }
robolectric = { group = "org.robolectric", name = "robolectric", version.ref = "robolectric" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }

[plugins]
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
android-library = { id = "com.android.library", version.ref = "androidGradlePlugin" }
android-test = { id = "com.android.test", version.ref = "androidGradlePlugin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
org-jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }



kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
#protobuf = { id = "com.google.protobuf", version.ref = "protobufPlugin" }
sonarqube = { id = "org.sonarqube", version.ref="sonarqube" }