client-ui-tests:
  type: instrumentation
  environment-variables:
    coverage: true
    coverageFile: /sdcard/coverage.ec
  device:
    - model: Pixel2
      version: 29
      locale: en
      orientation: portrait
  directories-to-pull: /sdcard
  record-video: false
 # results-bucket:
 # results-dir: